# Generated by Django 5.1.4 on 2025-02-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_chain", "0003_alter_approvalchain_minute"),
        ("minute", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minute",
            name="approval_chain",
            field=models.OneToOneField(
                blank=True,
                help_text="The approval chain linked to this minute.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_minute",
                to="approval_chain.approvalchain",
            ),
        ),
    ]
