# Generated by Django 5.1.4 on 2025-03-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minute", "0002_alter_minute_approval_chain"),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Optional attachment (PDF, image, Word, Excel, etc.).",
                null=True,
                upload_to="minute_attachments/",
            ),
        ),
    ]
