# Generated by Django 5.1.6 on 2025-02-22 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the department",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="dean",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned as the Dean of the Department (Optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dean_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned as the Head of Department (Optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
