# Generated by Django 5.1.4 on 2025-02-23 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalChain",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the approval chain",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the approval chain was created.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this approval chain.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_approval_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approver",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="The order of this approver in the chain."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Marked", "Marked"),
                            ("Returned", "Returned"),
                        ],
                        default="Pending",
                        help_text="Approval status of this approver.",
                        max_length=20,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this approver is the current active approver.",
                    ),
                ),
                (
                    "approval_chain",
                    models.ForeignKey(
                        help_text="The approval chain this approver belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvers",
                        to="approval_chain.approvalchain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user responsible for approving the minute.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("approval_chain", "user")},
            },
        ),
    ]
