# Generated by Django 5.1.4 on 2025-02-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_chain", "0002_initial"),
        ("minute", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalchain",
            name="minute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_chain_link_temp",
                to="minute.minute",
            ),
        ),
    ]
