# Generated by Django 5.1.4 on 2025-02-24 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_chain", "0003_alter_approvalchain_minute"),
        ("minute", "0002_alter_minute_approval_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalchain",
            name="minute",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_chain_link_temp",
                to="minute.minute",
            ),
        ),
    ]
